---

- include: ubuntu-14.04.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int < 15

- name: Set selinux permissive because tokens and selinux don't work together
  selinux: state=permissive policy={{ ansible_selinux.type }}
  when: ansible_selinux is defined and ansible_selinux.status == "enabled"

- name: Retrieve systemd files for github-release kube_source_type type
  include: retrieve-systemd-files.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int == 16

# Change default value of kube_source_type
- name: Force kube_source_type to github
  set_fact:
    kube_source_type: "github-release"
  when: ansible_distribution == 'Ubuntu'

- include: download_bins.yml
  when: kube_source_type == "github-release"
  tags:
    - binary-update
