---

- name: "Override docker config file directory for Debian"
  set_fact:
    docker_config_dir: "/etc/default"

- name: "Create config file directory"
  file: 
   path: "{{ docker_config_dir }}"
   state: directory

- name: "Install GPG key"
  command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 {% if http_proxy is defined -%}--keyserver-options http-proxy={{ http_proxy }} {% endif -%} --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

- name: "Configure apt repository"
  template: 
   src: "docker.list.j2" 
   dest: "/etc/apt/sources.list.d/docker.list"
  register: add_apt_source_docker

- name: "Update repository information"
  command: apt-get update
  when: add_apt_source_docker.changed

- name: "Install docker engine"
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: docker-engine
    state: latest

- name: "Create docker fact"
  set_fact:
    docker_use_upstart: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int < 15

- name: "Local vars for systemd installs"
  set_fact:
    docker_config_net: "{{ docker_config_dir }}/docker-network"
    docker_env_export: ""

- name: "Local vars for upstart installs"
  set_fact:
    docker_config_net: "{{ docker_config_dir }}/docker"
    docker_env_export: "export "
  when: docker_use_upstart

- name: "Verify docker config files exists"
  file: 
   path: "{{ docker_config_dir }}/{{ item }}" 
   state: touch
  changed_when: false
  with_items:
  - docker
  - docker-network

- name: "Turn down docker logging"
  lineinfile: dest={{ docker_config_dir }}/docker regexp=^OPTIONS= line=OPTIONS="--selinux-enabled --log-level=warn"
  notify:
    - restart docker
  when: docker_use_upstart
  tags: configure

- name: "Install no-proxy into docker(-network)"
  lineinfile: 
   dest: "{{ docker_config_net }}" 
   regexp: "^{{ docker_env_export }}no_proxy=" 
   line: "{{ docker_env_export }}no_proxy={{ no_proxy }}"
  when: no_proxy is defined
  notify:
    - restart docker
  tags: configure

- name: Enable Docker
  service: 
   name: docker  
   enabled: yes
  notify:
    - start docker
